[project]
name = "blockchain-audit"
authors = ["Developer"]
description = "A privacy-preserving blockchain audit system for tracking and verifying organizational wellness metrics"
telemetry = false
requirements = []
[contracts.organizational-wellness-audit]
path = "contracts/organizational-wellness-audit.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
